---
title: "MUSA 550 Final Project"
subtitle: "Assessing relationship between urban form and walkability in Kisumu, Kenya"
---

## Welcome

Kisumu is a port city in western Kenya at 1,131 m (3,711 ft) elevation. The port was founded in 1901 as the main inland terminal of the Uganda Railway and named Port Florence. As Kenya's third-largest city, Kisumu is a microcosm of the country's development trajectory. It grapples with the demands of urbanization while striving to provide for its residents' health, well-being, and rights. 

Kisumu's urban footprint today showcases a complex interplay of growth, history, and diverse land uses. The city, evolving from its historical origins, now balances modern development with its cultural and historical heritage. Its expansion reflects a range of functionalities, from residential and commercial spaces to industrial areas, all interwoven into the city's unique character. 

I am using scikit-learn for k-means clustering to classify Landsat 8 imagery for understanding urban landscapes in Kisumu. Then, I applied OSMnx for street network analysis in Kisumu to evaluate urban walkability, focusing on factors like street density and accessibility to amenities. This approach allowed me to assess the relationship between urban form and walkability in Kisumu.

## Potential Data Sources:

1. ESRIWorldImageryWaybackSatelliteData 

2. GoogleEarthEngine

3. OSMStreetMapsData










 
